### ISSUE TITLE
error: attribute 'setuptools-scm' missing

### ISSUE THREAD

**Issue by uvNikita** [nix-community/setup.nix#16]
Getting error when trying to follow tutorial from README, nixpkgs is 19.03.

setup.nix:

```
{ pkgs ? import <nixpkgs> {}
, pythonPackages ? pkgs.python3Packages
, setup ? import (fetchTarball {
    url = "https://github.com/datakurre/setup.nix/archive/v2.0.tar.gz";
    sha256 = "rgak3pg5nrrhxj2cws313jz80pmdys047ypnyhagvrfry5a9wa48";
  })
}:

setup {
  inherit pkgs pythonPackages;
  src = ./.;
}
```

Running:
`$ nix-shell setup.nix -A develop`

Results in error:
`error: attribute 'setuptools-scm' missing, at /nix/store/...-source/overrides.nix:155:10`

**Comment by datakurre** [comment]
Oh, sorry about that.

The fix is to add setuptools-scm into requirements.txt before generating requirements.nix.

You also might want to check the examples in the repo.

**Comment by datakurre** [comment]
That error comes from my “default overrides” been updated to include setuptools-scm for some package.

**Comment by uvNikita** [comment]
This solved this issue indeed, thanks! If I understand correctly, this is a workaround and will not be necessary in the future once it will be fixed in setup.nix?

**Comment by datakurre** [comment]
Probably. I recall that when I started this, nixpkgs did not yet have setuptools-scm
packages. Probably I only need to add default alias “setuptools-scm” = self.”setuptools_scm” to make it work...

**Comment by datakurre** [comment]
I just got blindly used to add it into requirements.txt and never looked back :)

**Comment by datakurre** [comment]
The latest version should have fixed this due to changes in pip2nix to detect most build and test dependencies.
