### ISSUE TITLE
Requirements question

### ISSUE THREAD

**Issue by takeda** [nix-community/setup.nix#8]
The setup.nix requires requirements.nix file, what can I do if my package has no Python dependencies?

Also, any way I can have pip2nix get dependencies from install_requires in setup.cfg instead of generating requirements.txt?

**Comment by datakurre** [comment]
If your package has no Python dependencies, you might be better of using `buildPythonPackage` function directly. This is tuned toward my use cases, where my projects have a lot of Python dependencies, and I need to be able to use different/missing versions than available nixpkgs and also in-house packages.

`pip2nix` does currently only support `requirements.txt`. Your issue might be better at its repository https://github.com/johbo/pip2nix To use `setup.cfg` you could write a small Python script that using `configparser` and write `requirements.txt` for `pip2nix`.

**Comment by takeda** [comment]
If you think that your solution could be adapted to work this way and you don't mind, I could try to do some work.

So far looked at `pypi2nix` and `pip2nix` and yours seems closest to what I think will work.

**Comment by datakurre** [comment]
@takeda I have chained packages with `setup.nix`, but `setup.nix` still relies on `pip2nix`.

In my use case developing packages usually requires more packages than just install_requires. Also, I don't want to pin version in setup.cfg. Therefore I was fine with having also requirements.txt. So, I'm having package direct requirements unpinned in setup.cfg, but then superset of those with all testing and QA (flake8, yapf, isort, ...) and required version pins in requirements.txt.

I have setup.nix or every package and chain them include them with something like

```nix
 (import (anything resolving to package code)/setup.nix { inherit pkgs pythonPackages; }).build
```

that calls the setup.nix with the package with the same pkgs and pythonPackages versions and returns the built python package.

**Comment by takeda** [comment]
@datakurre so in terms of setup.cfg vs requirements.txt we use them nearly the same.

I similarly don't have any versions pinned in setup.cfg, but instead of having for example requirements to run tests I use `tests_require` etc, requirements.txt is generated during deployment to pin to specific versions.

I'll try to play with it and see if I can get it to work.

I noticed that your nix code starts python to generate setup.json file with the config parsed. Not sure if it would fit here, but setuptools has command to parse it: https://setuptools.readthedocs.io/en/latest/setuptools.html#configuration-api

**Comment by datakurre** [comment]
The latest version should be able to discover most of the Python build and test dependencies due to development in pip2nix.
